package telas;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Kelvin E Miguel
 */
public class tela_principal extends javax.swing.JFrame {

    /**
     * Creates new form Tela_home
     */
    public tela_principal() {
        initComponents();
        btn_saida.setEnabled(true);
        txt_material.setEnabled(true);
        txt_nome_tecnico.setEnabled(false);
        txt_supervisor.setEnabled(false);
        txt_nome_material.setEnabled(false);
        txt_quantidade_por_super.setEnabled(false);
        txt_matricula_tecnico.requestFocus();
        tela_saida_material.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frm_principal = new javax.swing.JDesktopPane();
        lbl_titulo_form_principal = new javax.swing.JLabel();
        btn_home = new javax.swing.JButton();
        btn_estoque = new javax.swing.JButton();
        btn_cadastro = new javax.swing.JButton();
        btn_material = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn_saida = new javax.swing.JButton();
        tela_saida_material = new javax.swing.JInternalFrame();
        lbl_nome_tecnico = new javax.swing.JLabel();
        txt_supervisor = new javax.swing.JTextField();
        btn_confirmar_saida = new javax.swing.JButton();
        lbl_supervisor = new javax.swing.JLabel();
        txt_matricula_tecnico = new javax.swing.JTextField();
        lbl_matricula_tecnico = new javax.swing.JLabel();
        txt_nome_tecnico = new javax.swing.JTextField();
        lbl_cod_material = new javax.swing.JLabel();
        txt_material = new javax.swing.JTextField();
        btn_fechar_saida = new javax.swing.JButton();
        lbl_saida_material_titulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lbl_nome_material = new javax.swing.JLabel();
        txt_nome_material = new javax.swing.JTextField();
        lbl_total_deste_material = new javax.swing.JLabel();
        txt_quantidade_por_super = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");
        setName("tela_home"); // NOI18N

        frm_principal.setBackground(new java.awt.Color(240, 240, 240));

        lbl_titulo_form_principal.setFont(new java.awt.Font("Trajan Pro", 0, 36)); // NOI18N
        lbl_titulo_form_principal.setText("Controle de Estoque");

        btn_home.setText("HOME");

        btn_estoque.setText("ESTOQUE");

        btn_cadastro.setText("CADASTRO");
        btn_cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastroActionPerformed(evt);
            }
        });

        btn_material.setText("MATERIAL");
        btn_material.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_materialActionPerformed(evt);
            }
        });

        btn_saida.setText("SAÍDA");
        btn_saida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saidaActionPerformed(evt);
            }
        });

        tela_saida_material.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tela_saida_material.setTitle("Saida de Material");
        tela_saida_material.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tela_saida_material.setFocusCycleRoot(false);
        tela_saida_material.setVisible(true);
        tela_saida_material.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tela_saida_materialKeyPressed(evt);
            }
        });

        lbl_nome_tecnico.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_nome_tecnico.setText("Nome Técnico");

        txt_supervisor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btn_confirmar_saida.setText("Confirmar");
        btn_confirmar_saida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_confirmar_saidaActionPerformed(evt);
            }
        });
        btn_confirmar_saida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_confirmar_saidaKeyPressed(evt);
            }
        });

        lbl_supervisor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_supervisor.setText("Supervisor");

        txt_matricula_tecnico.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_matricula_tecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_matricula_tecnicoActionPerformed(evt);
            }
        });
        txt_matricula_tecnico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_matricula_tecnicoKeyPressed(evt);
            }
        });

        lbl_matricula_tecnico.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_matricula_tecnico.setText("Matricula");

        txt_nome_tecnico.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lbl_cod_material.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_cod_material.setText("Codigo Material");

        txt_material.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_material.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_materialActionPerformed(evt);
            }
        });

        btn_fechar_saida.setText("Fechar");
        btn_fechar_saida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fechar_saidaActionPerformed(evt);
            }
        });

        lbl_saida_material_titulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_saida_material_titulo.setText("Saida Material");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Material", "Quant"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        lbl_nome_material.setText("Nome Material");

        lbl_total_deste_material.setText("Total Deste Material");

        javax.swing.GroupLayout tela_saida_materialLayout = new javax.swing.GroupLayout(tela_saida_material.getContentPane());
        tela_saida_material.getContentPane().setLayout(tela_saida_materialLayout);
        tela_saida_materialLayout.setHorizontalGroup(
            tela_saida_materialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(tela_saida_materialLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tela_saida_materialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tela_saida_materialLayout.createSequentialGroup()
                        .addGroup(tela_saida_materialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tela_saida_materialLayout.createSequentialGroup()
                                .addGroup(tela_saida_materialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(tela_saida_materialLayout.createSequentialGroup()
                                        .addComponent(lbl_supervisor, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txt_supervisor))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(tela_saida_materialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_quantidade_por_super, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(tela_saida_materialLayout.createSequentialGroup()
                                        .addComponent(lbl_total_deste_material, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27))))
                            .addGroup(tela_saida_materialLayout.createSequentialGroup()
                                .addGroup(tela_saida_materialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_saida_material_titulo)
                                    .addComponent(txt_material, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(tela_saida_materialLayout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(lbl_cod_material, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(44, 44, 44)
                                        .addGroup(tela_saida_materialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_nome_material)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tela_saida_materialLayout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(txt_nome_material, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(tela_saida_materialLayout.createSequentialGroup()
                                        .addGroup(tela_saida_materialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_matricula_tecnico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbl_matricula_tecnico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(tela_saida_materialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(tela_saida_materialLayout.createSequentialGroup()
                                                .addGap(9, 9, 9)
                                                .addComponent(lbl_nome_tecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(tela_saida_materialLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txt_nome_tecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 34, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tela_saida_materialLayout.createSequentialGroup()
                        .addComponent(btn_confirmar_saida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_fechar_saida, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        tela_saida_materialLayout.setVerticalGroup(
            tela_saida_materialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tela_saida_materialLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tela_saida_materialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tela_saida_materialLayout.createSequentialGroup()
                        .addComponent(lbl_saida_material_titulo)
                        .addGap(18, 18, 18)
                        .addGroup(tela_saida_materialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_nome_tecnico)
                            .addComponent(lbl_matricula_tecnico))
                        .addGap(2, 2, 2)
                        .addGroup(tela_saida_materialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_matricula_tecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nome_tecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 32, Short.MAX_VALUE)
                        .addGroup(tela_saida_materialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tela_saida_materialLayout.createSequentialGroup()
                                .addComponent(lbl_cod_material)
                                .addGap(5, 5, 5))
                            .addGroup(tela_saida_materialLayout.createSequentialGroup()
                                .addComponent(lbl_nome_material)
                                .addGap(4, 4, 4)))
                        .addGroup(tela_saida_materialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_nome_material)
                            .addComponent(txt_material))
                        .addGap(18, 18, 18)
                        .addGroup(tela_saida_materialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tela_saida_materialLayout.createSequentialGroup()
                                .addComponent(lbl_supervisor)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(tela_saida_materialLayout.createSequentialGroup()
                                .addComponent(lbl_total_deste_material)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(tela_saida_materialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_quantidade_por_super, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                                    .addComponent(txt_supervisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(tela_saida_materialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_fechar_saida, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_confirmar_saida, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        frm_principal.setLayer(lbl_titulo_form_principal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        frm_principal.setLayer(btn_home, javax.swing.JLayeredPane.DEFAULT_LAYER);
        frm_principal.setLayer(btn_estoque, javax.swing.JLayeredPane.DEFAULT_LAYER);
        frm_principal.setLayer(btn_cadastro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        frm_principal.setLayer(btn_material, javax.swing.JLayeredPane.DEFAULT_LAYER);
        frm_principal.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        frm_principal.setLayer(btn_saida, javax.swing.JLayeredPane.DEFAULT_LAYER);
        frm_principal.setLayer(tela_saida_material, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout frm_principalLayout = new javax.swing.GroupLayout(frm_principal);
        frm_principal.setLayout(frm_principalLayout);
        frm_principalLayout.setHorizontalGroup(
            frm_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frm_principalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frm_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frm_principalLayout.createSequentialGroup()
                        .addGroup(frm_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_saida, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_cadastro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_estoque, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_home, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_material, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addComponent(tela_saida_material, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(frm_principalLayout.createSequentialGroup()
                        .addComponent(lbl_titulo_form_principal)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        frm_principalLayout.setVerticalGroup(
            frm_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frm_principalLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lbl_titulo_form_principal)
                .addGroup(frm_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frm_principalLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(btn_home, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_estoque, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_cadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_saida, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_material, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                        .addGap(249, 249, 249))
                    .addGroup(frm_principalLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(tela_saida_material, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(frm_principal, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(frm_principal)
        );

        setSize(new java.awt.Dimension(811, 689));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_saidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saidaActionPerformed
//        tela_saida saida = new tela_saida();
//        saida.setVisible(true);
        btn_saida.setEnabled(false);
        tela_saida_material.setVisible(true);
    }//GEN-LAST:event_btn_saidaActionPerformed

    private void btn_cadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastroActionPerformed
        tela_cadastro cadastro = new tela_cadastro();
        cadastro.setVisible(true);
    }//GEN-LAST:event_btn_cadastroActionPerformed

    private void btn_fechar_saidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fechar_saidaActionPerformed
        btn_saida.setEnabled(true);
        txt_matricula_tecnico.setText(null);

        txt_material.setText(null);
        txt_nome_tecnico.setText(null);
        txt_supervisor.setText(null);
        tela_saida_material.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_btn_fechar_saidaActionPerformed

    private void txt_materialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_materialActionPerformed
        txt_material.transferFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_materialActionPerformed

    private void tela_saida_materialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tela_saida_materialKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tela_saida_materialKeyPressed

    private void txt_matricula_tecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_matricula_tecnicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_matricula_tecnicoActionPerformed

    private void txt_matricula_tecnicoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_matricula_tecnicoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_matricula_tecnico.getText().equals("8870")) {
                txt_nome_tecnico.setText("Kelvin Josuel Coleti");
                txt_matricula_tecnico.transferFocus();
            } else if (txt_matricula_tecnico.getText().equals("2511")) {
                txt_nome_tecnico.setText("Luiz Miguel Dos Santos");
                txt_supervisor.setText("Fabio");
                txt_matricula_tecnico.transferFocus();
            } else {
                txt_matricula_tecnico.setText(null);
            }
        } else if (evt.getKeyCode() == KeyEvent.VK_BACK_SPACE) {
            txt_nome_tecnico.setText(null);
        }
    }//GEN-LAST:event_txt_matricula_tecnicoKeyPressed

    @SuppressWarnings("empty-statement")
    private void btn_confirmar_saidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_confirmar_saidaActionPerformed
        if (txt_matricula_tecnico.getText() != null) {
            if (txt_nome_tecnico.getText().equals("")) {
                txt_matricula_tecnico.requestFocus();
                JOptionPane.showMessageDialog(rootPane, "Preencha a Matricula do Tecnico", "Erro Ao Entregar", ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Entregue Para: \n " + txt_nome_tecnico.getText(), "Entregue com Suscesso", INFORMATION_MESSAGE);
                txt_matricula_tecnico.setText(null);
                txt_nome_tecnico.setText(null);
                txt_supervisor.setText(null);
                txt_material.setText(null);
                txt_matricula_tecnico.requestFocus();
            };
        }
// TODO add your handling code here:


    }//GEN-LAST:event_btn_confirmar_saidaActionPerformed

    private void btn_confirmar_saidaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_confirmar_saidaKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
         if (txt_matricula_tecnico.getText() != null) {
            if (txt_nome_tecnico.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Preencha a Matricula do Tecnico", "Erro Ao Entregar", ERROR_MESSAGE);
                txt_matricula_tecnico.requestFocus();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Entregue Para: \n " + txt_nome_tecnico.getText(), "Entregue com Suscesso", INFORMATION_MESSAGE);
                txt_matricula_tecnico.setText(null);
                txt_nome_tecnico.setText(null);
                txt_supervisor.setText(null);
                txt_material.setText(null);
                txt_matricula_tecnico.requestFocus();
            };
        }
    }

// TODO add your handling code here:
    }//GEN-LAST:event_btn_confirmar_saidaKeyPressed

    private void btn_materialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_materialActionPerformed
       
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_materialActionPerformed

public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_principal.class

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_principal.class

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_principal.class

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_principal.class

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadastro;
    private javax.swing.JButton btn_confirmar_saida;
    private javax.swing.JButton btn_estoque;
    private javax.swing.JButton btn_fechar_saida;
    private javax.swing.JButton btn_home;
    private javax.swing.JButton btn_material;
    private javax.swing.JButton btn_saida;
    private javax.swing.JDesktopPane frm_principal;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_cod_material;
    private javax.swing.JLabel lbl_matricula_tecnico;
    private javax.swing.JLabel lbl_nome_material;
    private javax.swing.JLabel lbl_nome_tecnico;
    private javax.swing.JLabel lbl_saida_material_titulo;
    private javax.swing.JLabel lbl_supervisor;
    private javax.swing.JLabel lbl_titulo_form_principal;
    private javax.swing.JLabel lbl_total_deste_material;
    private javax.swing.JInternalFrame tela_saida_material;
    private javax.swing.JTextField txt_material;
    private javax.swing.JTextField txt_matricula_tecnico;
    private javax.swing.JTextField txt_nome_material;
    private javax.swing.JTextField txt_nome_tecnico;
    private javax.swing.JTextField txt_quantidade_por_super;
    private javax.swing.JTextField txt_supervisor;
    // End of variables declaration//GEN-END:variables

}
